### ISSUE TITLE
Unable to compile on windows using msvc 14.0

### ISSUE THREAD

**Issue by odessy** [erikengervall/fast-find-in-files#10]
Error generated for header file<dirent.h>.
Also error generated from getline and operator<<

> yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
$ node-gyp rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  getFiles.cc
  index.cc
  printResults.cc
  queryFile.cc
..\src\queryFile.cc(1): fatal error C1083: Cannot open include file: 'dirent.h': No such file or directory [C:\Shopify\fast-find-in-files-master\build\binding.vcxproj]
..\src\getFiles.cc(1): fatal error C1083: Cannot open include file: 'dirent.h': No such file or directory [C:\Shopify\fast-find-in-files-master\build\binding.vcxproj]
  superSearch.cc
  win_delay_load_hook.cc
..\src\printResults.cc(11): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'std::string' (or there is no acceptable conversion) [C:\Shopify\fast-find-in-files-master\build\binding.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(497): note: could be 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::basic_streambuf<char,std::char_traits<char>> *)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(477): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(const void *)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(457): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(long double)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(437): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(double)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(417): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(float)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(396): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned __int64)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(376): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(__int64)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(355): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned long)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(335): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(long)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(315): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned int)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(290): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(int)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(270): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned short)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(236): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(short)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(216): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(bool)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(209): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::ios_base &(__cdecl *)(std::ios_base &))' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(202): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::basic_ios<char,std::char_traits<char>> &(__cdecl *)(std::basic_ios<char,std::char_traits<char>> &))' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(196): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::basic_ostream<char,std::char_traits<char>> &(__cdecl *)(std::basic_ostream<char,std::char_traits<char>> &))' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(694): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<char,std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const char *)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(741): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<char,std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,char)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(779): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const char *)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(826): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,char)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(952): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const signed char *)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(959): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,signed char)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(966): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const unsigned char *)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(973): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,unsigned char)' (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(983): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<char,std::char_traits<char>,std::string>(std::basic_ostream<char,std::char_traits<char>> &&,const _Ty &)'
          with
          [
              _Ty=std::string
          ] (compiling source file ..\src\printResults.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(1021): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<char,std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const std::error_code &)' (compiling source file ..\src\printResults.cc)
  ..\src\printResults.cc(11): note: while trying to match the argument list '(std::basic_ostream<char,std::char_traits<char>>, std::string)'
..\src\superSearch.cc(17): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' (or there is no acceptable conversion) [C:\Shopify\fast-find-in-files-master\build\binding.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(497): note: could be 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::basic_streambuf<char,std::char_traits<char>> *)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(477): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(const void *)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(457): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(long double)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(437): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(double)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(417): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(float)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(396): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned __int64)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(376): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(__int64)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(355): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned long)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(335): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(long)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(315): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned int)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(290): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(int)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(270): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(unsigned short)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(236): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(short)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(216): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(bool)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(209): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::ios_base &(__cdecl *)(std::ios_base &))' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(202): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::basic_ios<char,std::char_traits<char>> &(__cdecl *)(std::basic_ios<char,std::char_traits<char>> &))' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(196): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::basic_ostream<char,std::char_traits<char>> &(__cdecl *)(std::basic_ostream<char,std::char_traits<char>> &))' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(694): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<char,std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const char *)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(741): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<char,std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,char)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(779): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const char *)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(826): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,char)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(952): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const signed char *)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(959): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,signed char)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(966): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const unsigned char *)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(973): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,unsigned char)' (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(983): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<char,std::char_traits<char>,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>(std::basic_ostream<char,std::char_traits<char>> &&,const _Ty &)'
          with
          [
              _Ty=std::basic_string<char,std::char_traits<char>,std::allocator<char>>
          ] (compiling source file ..\src\superSearch.cc)
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ostream(1021): note: or       'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<char,std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const std::error_code &)' (compiling source file ..\src\superSearch.cc)
  ..\src\superSearch.cc(17): note: while trying to match the argument list '(std::basic_ostream<char,std::char_traits<char>>, std::basic_string<char,std::char_traits<char>,std::allocator<char>>)'
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
